client:
  meta: http://39.107.227.107:8081/meta/
  asset-header: http://39.107.227.107:8082/asset/header/
  asset-data: http://39.107.227.107:8083/asset/data/

server:
  port: 8084

spring:
  datasource:
#    url: jdbc:mysql:///xrhub
#    username: root
#    password: root
    url: jdbc:mysql://39.107.227.107:3306/xrhub?useUnicode=true&characterEncoding=UTF-8
    username: developer
    password: 0verwhelm4DEV
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: StroePool
      maximum-pool-size: 40
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 5120MB
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: online.xrhub.xrhubstore.entity
  configuration:
    cache-enabled: false

logging:
  level:
    online.xrhub.xrhubstore.mapper: debug
  path: /xrhub/store/log

upload:
  path: /xrhub/store/upload